<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-11T19:28:24 ICT" name="Default suite" finished-at="2023-04-11T19:28:35 ICT" duration-ms="10725">
    <groups>
    </groups>
    <test started-at="2023-04-11T19:28:24 ICT" name="Default test" finished-at="2023-04-11T19:28:35 ICT" duration-ms="10725">
      <class name="fpoly.SaveTestNGResultToExcel">
        <test-method is-config="true" signature="suiteSteUp()[pri:0, instance:fpoly.SaveTestNGResultToExcel@6e9175d8]" started-at="2023-04-11T19:28:24 ICT" name="suiteSteUp" finished-at="2023-04-11T19:28:24 ICT" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSteUp -->
        <test-method signature="LaunchWebsite()[pri:1, instance:fpoly.SaveTestNGResultToExcel@6e9175d8]" started-at="2023-04-11T19:28:24 ICT" name="LaunchWebsite" description="Opens the TestNG demo website for login test" finished-at="2023-04-11T19:28:34 ICT" duration-ms="10505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchWebsite -->
        <test-method signature="FillLoginDetails()[pri:2, instance:fpoly.SaveTestNGResultToExcel@6e9175d8]" started-at="2023-04-11T19:28:34 ICT" name="FillLoginDetails" description="Fill the Login Details" finished-at="2023-04-11T19:28:34 ICT" duration-ms="19" status="FAIL">
          <exception class="graphql.AssertException">
            <message>
              <![CDATA[condition expected to be true]]>
            </message>
            <full-stacktrace>
              <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at fpoly.SaveTestNGResultToExcel.FillLoginDetails(SaveTestNGResultToExcel.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- graphql.AssertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillLoginDetails -->
        <test-method signature="DoLogin()[pri:3, instance:fpoly.SaveTestNGResultToExcel@6e9175d8]" started-at="2023-04-11T19:28:34 ICT" name="DoLogin" description="Perform Login" finished-at="2023-04-11T19:28:34 ICT" duration-ms="10" status="FAIL">
          <exception class="graphql.AssertException">
            <message>
              <![CDATA[condition expected to be true]]>
            </message>
            <full-stacktrace>
              <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at fpoly.SaveTestNGResultToExcel.DoLogin(SaveTestNGResultToExcel.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- graphql.AssertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DoLogin -->
        <test-method is-config="true" signature="suiteTearDown()[pri:0, instance:fpoly.SaveTestNGResultToExcel@6e9175d8]" started-at="2023-04-11T19:28:34 ICT" name="suiteTearDown" finished-at="2023-04-11T19:28:35 ICT" duration-ms="118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteTearDown -->
      </class> <!-- fpoly.SaveTestNGResultToExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
